#!/usr/bin/env bash
# Ano Technology
# http://anotechnology.andib.org/
#
# Install with this command ( from your Termux(On Android) ):
#
# curl -L http://install.anovpn.andib.org | bash
#
# Make sure you have `curl` installed
echo Installing Ano Technology...
echo ...
echo ...
echo ...
echo Updating Version...
echo ...
echo ...
echo ...
echo Ano Technology successfully installed!
echo Now open Ano Browser and surf anonymous!
